import "./globals.css";
import Navbar from "@/components/Navbar";
import Sidebar from "@/components/Sidebar";

export const metadata = {
  title: "Admin dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <>
      <html lang="en">
        <body className="w-screen h-screen ">
          <main className="flex w-full h-full overflow-hidden select-none">
            {/* sidebar */}
            <aside className="h-full">
              <Sidebar />
            </aside>

            {/* navbar and children */}
            <div className="flex flex-col flex-1 overflow-hidden bg-slate-100">
              <nav className="h-[10vh]">
                <Navbar />
              </nav>

              {children}
            </div>
          </main>
        </body>
      </html>
    </>
  );
}
